### ISSUE TITLE
Not able to use this gem on macOS

### ISSUE THREAD

**Issue by lvolpe** [djellemah/upl#1]
Hi, was this gem tested on Mac? I'm trying to create a Rails app and use `upl` on Mac but it appears that a file is missing on the installation process.
macOS Big Sur.
version: 11.2.3

**Comment by djellemah** [comment]
I don't have MacOS.

Do you know which file is missing?

**Comment by djellemah** [comment]
For somebody who wants to help with macos

https://github.com/djellemah/upl/blob/3fd4d60ebdc1bf2e0fc2c227c69ae31988c502a2/.github/workflows/build.yml#L62

**Comment by djellemah** [comment]
Should now work ok on macos

**Comment by lvolpe** [comment]
Thanks 🙌🏼
